components:
  schemas:
    Contenido:
      type: object
      properties:
        id_contenido:
          type: integer
        nombre_contenido:
          type: string
        descripcion:
          type: string
        tipo:
          type: string
        duracion:
          type: string
info:
  description: API para gestionar productos
  title: API de Productos
  version: 1.0.0
openapi: 3.0.3
paths:
  /contenido:
    get:
      operationId: contenido_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Contenido'
                type: array
                x-content-type: application/json
          description: Lista de Contenido
      summary: Obtener contenido
      tags:
      - Contenido
      x-openapi-router-controller: swagger_server.controllers.contenido_controller
    post:
      operationId: contenido_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contenido'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contenido'
          description: Contenido creado correctamente
      summary: Crear Contenido
      tags:
      - Contenido
      x-openapi-router-controller: swagger_server.controllers.contenido_controller
  /contenido/{id_contenido_}:
    delete:
      operationId: contenido_id_contenido_delete
      parameters:
      - explode: false
        in: path
        name: id_contenido_
        required: true
        schema:
          type: integer
        style: simple
      responses:
        '204':
          description: Contenido eliminado correctamente
      summary: Eliminar contenido por ID
      tags:
      - Contenido
      x-openapi-router-controller: swagger_server.controllers.contenido_controller
    get:
      operationId: contenido_id_contenido_get
      parameters:
      - explode: false
        in: path
        name: id_contenido_
        required: true
        schema:
          type: integer
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contenido'
          description: Contenido encontrado
        '404':
          description: Contenido no encontrado
      summary: Obtener contenido por su id
      tags:
      - Contenido
      x-openapi-router-controller: swagger_server.controllers.contenido_controller
    put:
      operationId: contenido_id_contenido_put
      parameters:
      - explode: false
        in: path
        name: id_contenido_
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contenido'
        required: true
      responses:
        '200':
          description: Contenido actualizado correctamente
      summary: Actualizar contenido por ID
      tags:
      - Contenido
      x-openapi-router-controller: swagger_server.controllers.contenido_controller
