components:
  schemas:
    Nodo_perfil:
      type: object
      properties:
        perfil_id:
          type: integer
    Nodo_contenido:
      type: object
      properties:
        id_nodo_contenido:
          type: integer
    InteraccionRelation:
      type: object
      properties:
        source:
          type: string
        destination:
          type: string

info:
  description: API para gestionar nodos y relaciones
  title: API Neo4j
  version: 1.0.0
openapi: 3.0.3
paths:
  /nodo_perfil:
    get:
      operationId: nodo_perfil_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Nodo_perfil'
                type: array
          description: Lista de nodo_perfil
      summary: Obtener todos los nodo_perfil
      tags:
      - Nodo_perfil
      x-openapi-router-controller: swagger_server.controllers.nodo_perfil_controller
    post:
      operationId: nodo_perfil_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nodo_perfil'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nodo_perfil'
          description: Nodo creado
      summary: Crear nodo_perfil
      tags:
      - Nodo_perfil
      x-openapi-router-controller: swagger_server.controllers.nodo_perfil_controller
  /nodo_perfil/{id}:
    delete:
      operationId: nodo_perfil_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Nodo eliminado
      summary: Eliminar nodo_perfil por ID
      tags:
      - Nodo_perfil
      x-openapi-router-controller: swagger_server.controllers.nodo_perfil_controller
    get:
      operationId: nodo_perfil_getById
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nodo_perfil'
          description: Nodo encontrado
        '404':
          description: Nodo no encontrado
      summary: Obtener nodo_perfil por ID
      tags:
      - Nodo_perfil
      x-openapi-router-controller: swagger_server.controllers.nodo_perfil_controller
    put:
      operationId: nodo_perfil_put
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nodo_perfil'
        required: true
      responses:
        '200':
          description: Nodo actualizado
      summary: Actualizar nodo_perfil por ID
      tags:
      - Nodo_perfil
      x-openapi-router-controller: swagger_server.controllers.nodo_perfil_controller
  /nodo_contenido:
    get:
      operationId: nodo_contenido_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Nodo_contenido'
                type: array
          description: Lista de nodo_contenido
      summary: Obtener todos los nodo_contenido
      tags:
      - Nodo_contenido
      x-openapi-router-controller: swagger_server.controllers.nodo_contenido_controller
    post:
      operationId: nodo_contenido_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nodo_contenido'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nodo_contenido'
          description: Nodo creado
      summary: Crear nodo_contenido
      tags:
      - Nodo_contenido
      x-openapi-router-controller: swagger_server.controllers.nodo_contenido_controller
  /nodo_contenido/{id}:
    delete:
      operationId: nodo_contenido_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Nodo eliminado
      summary: Eliminar nodo_contenido por ID
      tags:
      - Nodo_contenido
      x-openapi-router-controller: swagger_server.controllers.nodo_contenido_controller
    get:
      operationId: nodo_contenido_getById
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Nodo_contenido'
          description: Nodo encontrado
        '404':
          description: Nodo no encontrado
      summary: Obtener nodo_contenido por ID
      tags:
      - Nodo_contenido
      x-openapi-router-controller: swagger_server.controllers.nodo_contenido_controller
    put:
      operationId: nodo_contenido_put
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nodo_contenido'
        required: true
      responses:
        '200':
          description: Nodo actualizado
      summary: Actualizar nodo_contenido por ID
      tags:
      - Nodo_contenido
      x-openapi-router-controller: swagger_server.controllers.nodo_contenido_controller

  /interaccion:
    get:
      operationId: interaccion_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/InteraccionRelation'
                type: array
          description: Lista de relaciones interaccion
      summary: Obtener todas las relaciones interaccion
      tags:
      - InteraccionRelation
      x-openapi-router-controller: swagger_server.controllers.interaccion_controller
    post:
      operationId: interaccion_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InteraccionRelation'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InteraccionRelation'
          description: Relación creada
      summary: Crear relación interaccion
      tags:
      - InteraccionRelation
      x-openapi-router-controller: swagger_server.controllers.interaccion_controller
  /interaccion/{source}/{destination}:
    delete:
      operationId: interaccion_delete
      parameters:
      - in: path
        name: source
        required: true
        schema:
          type: string
      - in: path
        name: destination
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Relación eliminada
      summary: Eliminar relación entre nodos
      tags:
      - InteraccionRelation
      x-openapi-router-controller: swagger_server.controllers.interaccion_controller
    get:
      operationId: interaccion_getByNodes
      parameters:
      - in: path
        name: source
        required: true
        schema:
          type: string
      - in: path
        name: destination
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InteraccionRelation'
          description: Relación encontrada
        '404':
          description: Relación no encontrada
      summary: Obtener relación entre nodos
      tags:
      - InteraccionRelation
      x-openapi-router-controller: swagger_server.controllers.interaccion_controller
    put:
      operationId: interaccion_put
      parameters:
      - in: path
        name: source
        required: true
        schema:
          type: string
      - in: path
        name: destination
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InteraccionRelation'
        required: true
      responses:
        '200':
          description: Relación actualizada
      summary: Actualizar relación entre nodos
      tags:
      - InteraccionRelation
      x-openapi-router-controller: swagger_server.controllers.interaccion_controller
